using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EMS
{
    public class Employee

    {
        //fields or data members
        public int Id { get; set; }//Autogenerated 4 digits
        public string Name { get; set; }
        public DateTime DateOfJoin { get; set; }
        public decimal Salary { get; set; }
        public Department Dept { get; set; }
        public bool InService { get; set; }
    }                                                                                               
}

